// flow-typed signature: 12bd5bfaf1c950090828024aaaaf7024
// flow-typed version: <<STUB>>/koa2-connect_v^1.0.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa2-connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa2-connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa2-connect/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa2-connect/dist/index.js' {
  declare module.exports: $Exports<'koa2-connect/dist/index'>;
}
